// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientStreamingInterceptor.proto

package clientStreamingInterceptor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pokemon struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  *PokemonTag `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pokemon) Reset()         { *m = Pokemon{} }
func (m *Pokemon) String() string { return proto.CompactTextString(m) }
func (*Pokemon) ProtoMessage()    {}
func (*Pokemon) Descriptor() ([]byte, []int) {
	return fileDescriptor_41870a27ee4ad95b, []int{0}
}

func (m *Pokemon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokemon.Unmarshal(m, b)
}
func (m *Pokemon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokemon.Marshal(b, m, deterministic)
}
func (m *Pokemon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokemon.Merge(m, src)
}
func (m *Pokemon) XXX_Size() int {
	return xxx_messageInfo_Pokemon.Size(m)
}
func (m *Pokemon) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokemon.DiscardUnknown(m)
}

var xxx_messageInfo_Pokemon proto.InternalMessageInfo

func (m *Pokemon) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pokemon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pokemon) GetTag() *PokemonTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type PokemonId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PokemonId) Reset()         { *m = PokemonId{} }
func (m *PokemonId) String() string { return proto.CompactTextString(m) }
func (*PokemonId) ProtoMessage()    {}
func (*PokemonId) Descriptor() ([]byte, []int) {
	return fileDescriptor_41870a27ee4ad95b, []int{1}
}

func (m *PokemonId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PokemonId.Unmarshal(m, b)
}
func (m *PokemonId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PokemonId.Marshal(b, m, deterministic)
}
func (m *PokemonId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PokemonId.Merge(m, src)
}
func (m *PokemonId) XXX_Size() int {
	return xxx_messageInfo_PokemonId.Size(m)
}
func (m *PokemonId) XXX_DiscardUnknown() {
	xxx_messageInfo_PokemonId.DiscardUnknown(m)
}

var xxx_messageInfo_PokemonId proto.InternalMessageInfo

func (m *PokemonId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PokemonTag struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PokemonTag) Reset()         { *m = PokemonTag{} }
func (m *PokemonTag) String() string { return proto.CompactTextString(m) }
func (*PokemonTag) ProtoMessage()    {}
func (*PokemonTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_41870a27ee4ad95b, []int{2}
}

func (m *PokemonTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PokemonTag.Unmarshal(m, b)
}
func (m *PokemonTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PokemonTag.Marshal(b, m, deterministic)
}
func (m *PokemonTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PokemonTag.Merge(m, src)
}
func (m *PokemonTag) XXX_Size() int {
	return xxx_messageInfo_PokemonTag.Size(m)
}
func (m *PokemonTag) XXX_DiscardUnknown() {
	xxx_messageInfo_PokemonTag.DiscardUnknown(m)
}

var xxx_messageInfo_PokemonTag proto.InternalMessageInfo

func (m *PokemonTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Pokemons struct {
	Pokemons             []*Pokemon `protobuf:"bytes,1,rep,name=pokemons,proto3" json:"pokemons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pokemons) Reset()         { *m = Pokemons{} }
func (m *Pokemons) String() string { return proto.CompactTextString(m) }
func (*Pokemons) ProtoMessage()    {}
func (*Pokemons) Descriptor() ([]byte, []int) {
	return fileDescriptor_41870a27ee4ad95b, []int{3}
}

func (m *Pokemons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokemons.Unmarshal(m, b)
}
func (m *Pokemons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokemons.Marshal(b, m, deterministic)
}
func (m *Pokemons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokemons.Merge(m, src)
}
func (m *Pokemons) XXX_Size() int {
	return xxx_messageInfo_Pokemons.Size(m)
}
func (m *Pokemons) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokemons.DiscardUnknown(m)
}

var xxx_messageInfo_Pokemons proto.InternalMessageInfo

func (m *Pokemons) GetPokemons() []*Pokemon {
	if m != nil {
		return m.Pokemons
	}
	return nil
}

func init() {
	proto.RegisterType((*Pokemon)(nil), "Pokemon")
	proto.RegisterType((*PokemonId)(nil), "PokemonId")
	proto.RegisterType((*PokemonTag)(nil), "PokemonTag")
	proto.RegisterType((*Pokemons)(nil), "Pokemons")
}

func init() { proto.RegisterFile("clientStreamingInterceptor.proto", fileDescriptor_41870a27ee4ad95b) }

var fileDescriptor_41870a27ee4ad95b = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xcd, 0x4a, 0xc4, 0x30,
	0x18, 0x24, 0xad, 0x3f, 0xcd, 0x57, 0x58, 0x21, 0x78, 0x08, 0x2b, 0x42, 0x08, 0x1e, 0x02, 0x42,
	0x91, 0xfa, 0x06, 0xde, 0x16, 0x3c, 0x48, 0xd6, 0x17, 0x88, 0xcd, 0x47, 0x08, 0x6e, 0x93, 0x92,
	0x8d, 0x0b, 0xbe, 0xbd, 0x6c, 0x4d, 0x77, 0xc5, 0xdb, 0xcc, 0x64, 0x26, 0x99, 0x09, 0x88, 0x61,
	0xe7, 0x31, 0xe4, 0x6d, 0x4e, 0x68, 0x46, 0x1f, 0xdc, 0x26, 0x64, 0x4c, 0x03, 0x4e, 0x39, 0xa6,
	0x6e, 0x4a, 0x31, 0x47, 0xf9, 0x0a, 0xd7, 0x6f, 0xf1, 0x13, 0xc7, 0x18, 0xd8, 0x0a, 0x2a, 0x6f,
	0x39, 0x11, 0x44, 0xd5, 0xba, 0xf2, 0x96, 0x31, 0xb8, 0x08, 0x66, 0x44, 0x5e, 0x09, 0xa2, 0xa8,
	0x9e, 0x31, 0xbb, 0x87, 0x3a, 0x1b, 0xc7, 0x6b, 0x41, 0x54, 0xdb, 0xb7, 0x5d, 0x89, 0xbe, 0x1b,
	0xa7, 0x8f, 0xba, 0xbc, 0x03, 0x5a, 0xa4, 0x8d, 0xfd, 0x7f, 0x9f, 0x94, 0x00, 0x67, 0x3f, 0xbb,
	0x85, 0xcb, 0x83, 0xd9, 0x7d, 0xe1, 0x6c, 0xa0, 0xfa, 0x97, 0xc8, 0x27, 0x68, 0x8a, 0x67, 0xcf,
	0x1e, 0xa0, 0x99, 0x0a, 0xe6, 0x44, 0xd4, 0xaa, 0xed, 0x9b, 0xe5, 0x41, 0x7d, 0x3a, 0xe9, 0x0d,
	0xac, 0x8a, 0xb8, 0xc5, 0x74, 0xf0, 0x03, 0x32, 0x09, 0x60, 0xac, 0x5d, 0x56, 0x9d, 0x32, 0x6b,
	0xe8, 0xce, 0xdd, 0x1e, 0xe1, 0xc6, 0x61, 0x2e, 0xfc, 0xe5, 0xfb, 0x58, 0xe8, 0xef, 0x9a, 0x35,
	0x5d, 0xc8, 0x5e, 0x91, 0x8f, 0xab, 0xf9, 0xab, 0x9e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xee, 0x05, 0x24, 0x4e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokemonServiceClient is the client API for PokemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokemonServiceClient interface {
	AddPokemon(ctx context.Context, in *Pokemon, opts ...grpc.CallOption) (*PokemonId, error)
	GetPokemonByTag(ctx context.Context, opts ...grpc.CallOption) (PokemonService_GetPokemonByTagClient, error)
}

type pokemonServiceClient struct {
	cc *grpc.ClientConn
}

func NewPokemonServiceClient(cc *grpc.ClientConn) PokemonServiceClient {
	return &pokemonServiceClient{cc}
}

func (c *pokemonServiceClient) AddPokemon(ctx context.Context, in *Pokemon, opts ...grpc.CallOption) (*PokemonId, error) {
	out := new(PokemonId)
	err := c.cc.Invoke(ctx, "/PokemonService/addPokemon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokemonServiceClient) GetPokemonByTag(ctx context.Context, opts ...grpc.CallOption) (PokemonService_GetPokemonByTagClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PokemonService_serviceDesc.Streams[0], "/PokemonService/getPokemonByTag", opts...)
	if err != nil {
		return nil, err
	}
	x := &pokemonServiceGetPokemonByTagClient{stream}
	return x, nil
}

type PokemonService_GetPokemonByTagClient interface {
	Send(*PokemonTag) error
	CloseAndRecv() (*Pokemons, error)
	grpc.ClientStream
}

type pokemonServiceGetPokemonByTagClient struct {
	grpc.ClientStream
}

func (x *pokemonServiceGetPokemonByTagClient) Send(m *PokemonTag) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pokemonServiceGetPokemonByTagClient) CloseAndRecv() (*Pokemons, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Pokemons)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PokemonServiceServer is the server API for PokemonService service.
type PokemonServiceServer interface {
	AddPokemon(context.Context, *Pokemon) (*PokemonId, error)
	GetPokemonByTag(PokemonService_GetPokemonByTagServer) error
}

// UnimplementedPokemonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPokemonServiceServer struct {
}

func (*UnimplementedPokemonServiceServer) AddPokemon(ctx context.Context, req *Pokemon) (*PokemonId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPokemon not implemented")
}
func (*UnimplementedPokemonServiceServer) GetPokemonByTag(srv PokemonService_GetPokemonByTagServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPokemonByTag not implemented")
}

func RegisterPokemonServiceServer(s *grpc.Server, srv PokemonServiceServer) {
	s.RegisterService(&_PokemonService_serviceDesc, srv)
}

func _PokemonService_AddPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pokemon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServiceServer).AddPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PokemonService/AddPokemon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServiceServer).AddPokemon(ctx, req.(*Pokemon))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokemonService_GetPokemonByTag_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PokemonServiceServer).GetPokemonByTag(&pokemonServiceGetPokemonByTagServer{stream})
}

type PokemonService_GetPokemonByTagServer interface {
	SendAndClose(*Pokemons) error
	Recv() (*PokemonTag, error)
	grpc.ServerStream
}

type pokemonServiceGetPokemonByTagServer struct {
	grpc.ServerStream
}

func (x *pokemonServiceGetPokemonByTagServer) SendAndClose(m *Pokemons) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pokemonServiceGetPokemonByTagServer) Recv() (*PokemonTag, error) {
	m := new(PokemonTag)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PokemonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PokemonService",
	HandlerType: (*PokemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addPokemon",
			Handler:    _PokemonService_AddPokemon_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getPokemonByTag",
			Handler:       _PokemonService_GetPokemonByTag_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "clientStreamingInterceptor.proto",
}
