// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ch2/pokemon/pokemon.proto

package pokemon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PokemonID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PokemonID) Reset()         { *m = PokemonID{} }
func (m *PokemonID) String() string { return proto.CompactTextString(m) }
func (*PokemonID) ProtoMessage()    {}
func (*PokemonID) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a7efae5fdedccb, []int{0}
}

func (m *PokemonID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PokemonID.Unmarshal(m, b)
}
func (m *PokemonID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PokemonID.Marshal(b, m, deterministic)
}
func (m *PokemonID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PokemonID.Merge(m, src)
}
func (m *PokemonID) XXX_Size() int {
	return xxx_messageInfo_PokemonID.Size(m)
}
func (m *PokemonID) XXX_DiscardUnknown() {
	xxx_messageInfo_PokemonID.DiscardUnknown(m)
}

var xxx_messageInfo_PokemonID proto.InternalMessageInfo

func (m *PokemonID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Pokemon struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attack               uint64   `protobuf:"varint,2,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense              uint64   `protobuf:"varint,3,opt,name=defense,proto3" json:"defense,omitempty"`
	SpAttack             uint64   `protobuf:"varint,4,opt,name=spAttack,proto3" json:"spAttack,omitempty"`
	SpDefense            uint64   `protobuf:"varint,5,opt,name=spDefense,proto3" json:"spDefense,omitempty"`
	Speed                uint64   `protobuf:"varint,6,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pokemon) Reset()         { *m = Pokemon{} }
func (m *Pokemon) String() string { return proto.CompactTextString(m) }
func (*Pokemon) ProtoMessage()    {}
func (*Pokemon) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a7efae5fdedccb, []int{1}
}

func (m *Pokemon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokemon.Unmarshal(m, b)
}
func (m *Pokemon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokemon.Marshal(b, m, deterministic)
}
func (m *Pokemon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokemon.Merge(m, src)
}
func (m *Pokemon) XXX_Size() int {
	return xxx_messageInfo_Pokemon.Size(m)
}
func (m *Pokemon) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokemon.DiscardUnknown(m)
}

var xxx_messageInfo_Pokemon proto.InternalMessageInfo

func (m *Pokemon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pokemon) GetAttack() uint64 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *Pokemon) GetDefense() uint64 {
	if m != nil {
		return m.Defense
	}
	return 0
}

func (m *Pokemon) GetSpAttack() uint64 {
	if m != nil {
		return m.SpAttack
	}
	return 0
}

func (m *Pokemon) GetSpDefense() uint64 {
	if m != nil {
		return m.SpDefense
	}
	return 0
}

func (m *Pokemon) GetSpeed() uint64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func init() {
	proto.RegisterType((*PokemonID)(nil), "pokemon.PokemonID")
	proto.RegisterType((*Pokemon)(nil), "pokemon.Pokemon")
}

func init() { proto.RegisterFile("ch2/pokemon/pokemon.proto", fileDescriptor_48a7efae5fdedccb) }

var fileDescriptor_48a7efae5fdedccb = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x83, 0x52, 0x90, 0xf1, 0x62, 0x26, 0xc6, 0xac, 0xc4, 0x43, 0xed, 0xa9, 0x27, 0x88,
	0xf4, 0x09, 0xd4, 0x5e, 0xbc, 0x35, 0x1c, 0xbd, 0x6d, 0x61, 0x80, 0xa6, 0xec, 0x9f, 0xc0, 0x62,
	0xe2, 0xd3, 0xf8, 0xaa, 0xa6, 0x0b, 0x8b, 0x46, 0x7b, 0xda, 0xf9, 0xcd, 0x37, 0xdf, 0x66, 0xbe,
	0x0c, 0xdc, 0x17, 0x4d, 0x96, 0x6a, 0x75, 0x24, 0xa1, 0xa4, 0x7b, 0x13, 0xdd, 0x29, 0xa3, 0x30,
	0x9c, 0x70, 0xf5, 0x08, 0xd1, 0x6e, 0x2c, 0xdf, 0xb6, 0x78, 0x0b, 0x8b, 0x0f, 0xde, 0x0e, 0xc4,
	0xbc, 0xa5, 0xb7, 0x8e, 0xf2, 0x11, 0x56, 0x5f, 0x1e, 0x84, 0xd3, 0x0c, 0x22, 0xf8, 0x92, 0x0b,
	0x37, 0x60, 0x6b, 0xbc, 0x83, 0x80, 0x1b, 0xc3, 0x8b, 0x23, 0xbb, 0x58, 0x7a, 0x6b, 0x3f, 0x9f,
	0x08, 0x19, 0x84, 0x25, 0x55, 0x24, 0x7b, 0x62, 0x97, 0x56, 0x70, 0x88, 0x31, 0x5c, 0xf5, 0xfa,
	0x79, 0xf4, 0xf8, 0x56, 0x9a, 0x19, 0x1f, 0x20, 0xea, 0xf5, 0x76, 0xf2, 0x2d, 0xac, 0xf8, 0xd3,
	0x38, 0x6d, 0xd8, 0x6b, 0xa2, 0x92, 0x05, 0x56, 0x19, 0x21, 0x1b, 0xe0, 0xda, 0x85, 0x90, 0x95,
	0xc2, 0x0c, 0xa0, 0x26, 0x33, 0xaf, 0x9c, 0xb8, 0xe8, 0x73, 0xd0, 0xf8, 0xe6, 0x6f, 0xef, 0xe4,
	0xe1, 0x65, 0xe9, 0xe8, 0x9f, 0x1e, 0x9f, 0xf9, 0xe5, 0x65, 0xf3, 0xfe, 0x54, 0x1f, 0x4c, 0x33,
	0xec, 0x93, 0x42, 0x89, 0x54, 0x70, 0xa9, 0x2a, 0xd3, 0x50, 0x7b, 0x50, 0x92, 0x77, 0xe2, 0x33,
	0x6d, 0x89, 0x77, 0xb2, 0xce, 0x77, 0xaf, 0xe9, 0xaf, 0x3b, 0xec, 0x03, 0x7b, 0x80, 0xcd, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xa1, 0x46, 0xc9, 0x9d, 0x01, 0x00, 0x00,
}
